### ISSUE TITLE
Create an About Page

### ISSUE THREAD

**Issue by vindzhev** [vindzhev/HTML-CSS-Teamwork-Project#4]

**Comment by daniel-tsonkov** [comment]
Така е много трудно или ти ме намери в скайп tanhoyzer или си дай ти скайпа аз да те намеря.

**Comment by nikolovns** [comment]
nikolov_n_s е моят скайп


-------- Оригинално писмо --------
От:  daniel-tsonkov  
Относно: Re: [HTML-CSS-Teamwork-Project] Create an About Page (#4)
До: vindzhev/HTML-CSS-Teamwork-Project  
Изпратено на: Сряда, 2015, Февруари 18 18:58:36 EET


 Така е много трудно или ти ме намери в скайп tanhoyzer или си дай ти скайпа аз да те намеря.

**Comment by vindzhev** [comment]
Не знам какво му е трудното. Ако имаш някакви въпроси, може да ме намериш
във facebook или в университета. Всеки ден съм там, почти по цял ден. Сори,
но скайп не ползвам.

На Thu Feb 19 2015 at 10:23:50 nikolovns <notifications@github.com> написа:

**Comment by daniel-tsonkov** [comment]
Аз пък фейсбук не ползвам. :) интересна работа. ок Ще разчитаме на директен контакт.

**Comment by vindzhev** [comment]
Утре ще има Lab и ние ще сме в унито от към 14:00 часа. Имаш ли възможност
да дойдеш?

На Thu Feb 19 2015 at 15:35:29 daniel-tsonkov <notifications@github.com>
написа:

**Comment by daniel-tsonkov** [comment]
Никакъв шанс да дойда утре :( Всички останали дни без вторник и събота другата седмица съм на линия. Само кажете кога.

**Comment by vindzhev** [comment]
Понеделник, преди лекцията?

На Thu Feb 19 2015 at 8:14:13 PM daniel-tsonkov <notifications@github.com>
написа:

**Comment by daniel-tsonkov** [comment]
Супер :)

**Comment by nikolovns** [comment]
Момчета, аз понеже не съм много на ти с гитхъб и гледам, че тук има дискусия ще пиша направо тук. Доиде ми идея за страницата - да не си играем да правим колажи и т.н. ще отнеме повече време и нямаме много снимки. Вместо това нека страницата да е за това - кой на какви игри обича да играе - от старите. И текста ще измислим по-лесно. Пример - Наков обича да играе на Соник защото любимият му цвят е син и обича да събира стотинки. Нещо такова. А Богомил обича да играе на тетрис, защото обича да съединява назъбени матрици след като ги ревърсне ... такива неща. Какво ще кажете

**Comment by daniel-tsonkov** [comment]
Каквото изберете а за гитхъба ще ти покажа доста е лесно




 >-------- Оригинално писмо --------
 >От:  nikolovns 
 >Относно: Re: [HTML-CSS-Teamwork-Project] Create an About Page (#4)
 >До: vindzhev/HTML-CSS-Teamwork-Project 
 >Изпратено на: Събота, 2015, Февруари 21 12:56:36 EET
 >
 >
 >
 >Момчета, аз понеже не съм много на ти с гитхъб и гледам, че тук има дискусия ще пиша направо тук. Доиде ми идея за страницата - да не си играем да правим колажи и т.н. ще отнеме повече време и нямаме много снимки. Вместо това нека страницата да е за това - кой на какви игри обича да играе - от старите. И текста ще измислим по-лесно. Пример - Наков обича да играе на Соник защото любимият му цвят е син и обича да събира стотинки. Нещо такова. А Богомил обича да играе на тетрис, защото обича да съединява назъбени матрици след като ги ревърсне ... такива 
 неща. Какво ще кажете
